site_name: My Docs
theme: 
  name: windmill-dark

plugins:
  - search
  - multirepo:
      cleanup: true
      repos:
        - section: 'HomeLab'
          import_url: 'https://github.com/aldobettega/HomeLab'

nav:
  - Home: index.md