site_name: My Docs
theme: 
  name: windmill-dark

markdown_extensions:
  - attr_list

plugins:
  - search
  - multirepo:
      cleanup: true
      repos:
        - section: 'HomeLab'
          import_url: 'https://github.com/aldobettega/HomeLab?branch=main'
        - section: 'HashIdentifier'
          import_url: 'https://github.com/aldobettega/HashIdentifier/tree/main/Documentazione?branch=main'